### ISSUE TITLE
the modem does not turn on when powered by the battery

### ISSUE THREAD

**Issue by Aguilaaar** [Xinyuan-LilyGO/LilyGO-T-A76XX#100]
I have the board with the A7608SA-H modem, and everything works very well when I'm using power via the USB-C cable. But when I switch to the battery, the modem does not turn on, the ESP works normally, runs the code, sends commands to the modem, but it does not respond.
I have two identical boards and both have the same problem, with my code or with examples here.
Do I need to do anything different to use with batteries?

**Comment by lewisxhe** [comment]
Which example to use

**Comment by Aguilaaar** [comment]
I tried many of these that are here https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/tree/main/examples
I believe that everyone who uses a GPRS connection

**Comment by Aguilaaar** [comment]
I just found my mistake!
I studied the schematic files and saw that I need to keep ESP pin 12 high, as shown in the T-A7608X-V1.0.pdf file.
I hadn't found this information anywhere else.

**Comment by lewisxhe** [comment]
POWERON MODEM is included in every example. Didn’t you see it?
