### ISSUE TITLE
SD card mount failed

### ISSUE THREAD

**Issue by br4593** [Xinyuan-LilyGO/LilyGO-T-A76XX#111]
Hi,

I inserted an SD card to the built in card slot of the T-7670G but when I run the SDCard example from the official github library (https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/), I get an "Card Mount Failed" error.

I have tried two different SD cards, neither one works:

San Disk 32GB SDHC with the following format:

<img width="188" alt="32gb" src="https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/112381346/31667d53-3018-40e1-bc4b-5a8d6bc10215">

San Disk 64GB SDXC with the following format:
<img width="186" alt="64gb" src="https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/112381346/e06ac21e-ffb8-45be-ae68-377b6458708b">

I am running with the official SD card example with no change to the code, so I assume the SPI pinout is correct.
Any ideas?

**Comment by lewisxhe** [comment]
Is the board selected correctly? Is the board selected LILYGO_T_A7670?

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/22990954/158bcb35-1c68-4d60-988a-b1abc7cddc29)

**Comment by br4593** [comment]
> ![image](https://private-user-images.githubusercontent.com/22990954/346980217-158bcb35-1c68-4d60-988a-b1abc7cddc29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NDY0NDUsIm5iZiI6MTcyMTU0NjE0NSwicGF0aCI6Ii8yMjk5MDk1NC8zNDY5ODAyMTctMTU4YmNiMzUtMWM2OC00ZDYwLTk4OGEtYjFhYmM3Y2RkYzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDA3MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwOTMwNGJlMmVhN2IwYTgxODU2ZDlhNDZiN2EyYTExNjI2MTQwZDAwY2MwM2M5Y2UwZDViYjhiZGE2OWI2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.paMNOmcj1yxF8-XnblIiDg58p50eclLE9cOyg0La5zw)

Yep. Here is how it looks like:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/9b14109e-52da-49a9-b959-674f8f33aa73">

**Comment by lewisxhe** [comment]
If replacing the SD card does not work, then it is certain that there is a problem with the card slot. Contact customer service for after-sales service.
