### ISSUE TITLE
[LilyGO T-A7670] Read battery percentage

### ISSUE THREAD

**Issue by garispe** [Xinyuan-LilyGO/LilyGO-T-A76XX#112]
> ⚠️ This is not an issue.

I am using a T-A7670[SA] and, I want to know how can I get the current battery percentage?

**Comment by HDC67** [comment]
Try here :
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/33

Newer versions have a voltage divider. Older versions you could easily add one yourself.
