### ISSUE TITLE
A7670G Traccar

### ISSUE THREAD

**Issue by lucioborges** [Xinyuan-LilyGO/LilyGO-T-A76XX#116]
I'm trying to configure an A7670G with Traccar, but the codes don't work for this modem.
Can anyone help?

**Comment by lewisxhe** [comment]
7670G does not support GPS

**Comment by lucioborges** [comment]
This module does not have GNNS, but it has a GPS on ESP pins 21 and 22.
#define GPS_TX_PIN 21
#define GPS_RX_PIN 22
Thank you!
