### ISSUE TITLE
Issue using the modem.getTemperature() function

### ISSUE THREAD

**Issue by Guiboy** [Xinyuan-LilyGO/LilyGO-T-A76XX#123]
Hello,
I receive erratic data when using customized TinyGsm library (the one provided in the lib download package for A7670E)  

here is the code I use :
$temp = modem.getTemperature();

When I use the TinyGSM lib which is published for Arduino IDE with my A7600E card, I receive a consistent temp value

when I use the TinyGSM lib provided for A7670E card (installed manually by extracting the zip file to my Arduino IDE library folder), I receive most of the time 28 deg Celsius or a wrong temperature (very high or very low).
To avoid mistaken data I repeat temperature reading for around 50 times until I receive something else than 28 deg and <200 deg, but this is sometime not enough

Can someone tell me how to overcome this issue?
it looks like a library bug

thanks a lot
Guillaume

**Comment by lewisxhe** [comment]
I also got about 28°C in my test, but if I blow the module with a hot air blower, the temperature will rise. The accuracy of the module is very low. If you want to obtain the ambient temperature, an external sensor is more suitable.
