### ISSUE TITLE
ReadBattery sketch

### ISSUE THREAD

**Issue by Hydra-Gituser** [Xinyuan-LilyGO/LilyGO-T-A76XX#126]
Hi Lewis, I have a new question for you.
Your sketch "ReadBattery" uses a deprecated calibration library so I wonder if you would be able to update the sketch to use the new library?

Thanks.

**Comment by lewisxhe** [comment]
Done.  The traditional API has been removed. Using the Arduino API will automatically calibrate during initialization.
