### ISSUE TITLE
GPSShield Example Returns INVALID Location and Incorrect Date/Time

### ISSUE THREAD

**Issue by georgelviv** [Xinyuan-LilyGO/LilyGO-T-A76XX#127]
Hello!

I recently purchased the A7670G R2 with GPS and tried running the **examples/GPSShield** from the provided examples. However, the output consistently returns an invalid location and an incorrect date/time. Below is the output I receive:

`Location: INVALID  Date/Time: 0/0/2000 00:00:00.00`

I can confirm I have external GPS module on board

![2024-08-21 10 37 03](https://github.com/user-attachments/assets/37a30f0b-8626-4999-a734-82c9c18189a3)

I've also tried running **examples/GPS_NMEA_Output**, and received following errors

<img width="657" alt="image" src="https://github.com/user-attachments/assets/21ccb027-5063-4524-9c73-bd222ad498c8">

**Comment by lewisxhe** [comment]
I added a warning that will appear if GPS is not present.

If there is no warning, it means that GPS is already connected. Please place the board where the sky is visible for positioning.

**Comment by georgelviv** [comment]
I've checked outdoor, works great, thanks!
