### ISSUE TITLE
Free Pinout A7670G

### ISSUE THREAD

**Issue by rammos92** [Xinyuan-LilyGO/LilyGO-T-A76XX#129]
There are a free pins to use for relay's please wait for answer

**Comment by lewisxhe** [comment]
Here you can find the pins that have been used. Other undefined pins can be used.
[utilities.h](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/examples/ATdebug/utilities.h)
![image](https://github.com/user-attachments/assets/280de53e-30cc-45b1-a859-9c448e3fee01)

**Comment by rammos92** [comment]
I try this , but i have the A7670G v 1.3 
When i choose 34 as  free pin or a any free pin like want to use interrupter on off ( free pin and GND ) or ( free pin and VBUS ) value of this pin not changed

**Comment by lewisxhe** [comment]
io34只能作为输入，而且必须要有在不上拉电阻

**Comment by lewisxhe** [comment]
io34 can only be used as input and must have an external pull-up resistor

**Comment by rammos92** [comment]
Which io u suggest to use as interrupter ( like proximity sensors ....)
