### ISSUE TITLE
Voice calls

### ISSUE THREAD

**Issue by Jvf01** [Xinyuan-LilyGO/LilyGO-T-A76XX#130]
I recently purchased the LILYGO® TTGO T-A7670G/E/SA R2 4G card and I need to know if I can connect a microphone and speaker to make voice calls.
thank you

**Comment by lewisxhe** [comment]
See [FAQ -  How to use voice call example?](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX#6%EF%B8%8F%E2%83%A3-faq)

**Comment by Jvf01** [comment]
Thanks.  Apparently this card supports voice calls.  Can you send me a schematic for soldering the microphone and speaker?
Thank you

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/709f890e-5fcf-4d31-a111-cb7cd5c10c39)
There is no connection diagram for the LilyGo, so I can only simply tell you where the solder points are.

**Comment by Jvf01** [comment]
Ok.

Thank you, I wil try

A quinta, 29/08/2024, 09:38, Lewis He ***@***.***> escreveu:
