### ISSUE TITLE
SIM7672G - Incoming Call - Trigger Webhook

### ISSUE THREAD

**Issue by macflyhub** [Xinyuan-LilyGO/LilyGO-T-A76XX#131]
All I need is for the SIM7672G to wait for a call (just ring once) and then send a webhook (post) with the Caller ID/Phone number using the 4G network and get a reply code which will be a response of 0 or 1 to action a relay aka pull a pin high on the ESP.
So I thought this would be a cake walk but its not as easy as I thought mostly because of the figuring out how the caller ID and webhook side works.
Anyone got some sample code that can get me up and running ?
Please!

**Comment by lewisxhe** [comment]
SIM7670G does not support SMS and voice calls

**Comment by lewisxhe** [comment]
A7608 supports voice
