### ISSUE TITLE
GPS Not Working on LilyGO A7670G Board

### ISSUE THREAD

**Issue by embedded-systems-lol** [Xinyuan-LilyGO/LilyGO-T-A76XX#132]
I am experiencing issues with the GPS functionality on my LilyGO A7670G board. Despite following the recommended steps to test the GPS, I am unable to get any NMEA sentences output or successful GPS initialization. Below are the details of my troubleshooting process and the output logs. What tha fuck could went wrong ?

**Board Details:**
Model: LilyGO A7670G
Module Label Image: attached below
Firmware: GPS_NMEA_Output
Platform: PlatformIO

**Steps Taken:**
Built and uploaded the GPS_NMEA_Output firmware to the board.
Monitored the serial output to check for NMEA sentences.
Attempted multiple times to initialize GPS with the AT+CGNSSPWR=1 command.

**Observed Behavior**
The serial monitor repeatedly returns the following error message:
`AT+CGNSSPWR=1
ERROR
GPS startup failed. Please check whether the board you ordered contains GPS function.
The log also suggests that the board might not support GPS, despite being labeled as a GPS-capable model.`

**log from GPS_NMEA_Output**
[GPS_NMEA_Output.log](https://github.com/user-attachments/files/16770193/GPS_NMEA_Output.log)

ordered from aliexpress this one
[https://www.aliexpress.com/item/1005003036514769.html?srcSns=sns_Copy&spreadType=socialShare&bizType=ProductDetail&social_params=21595548853&aff_fcid=e42d3eefa5d8453ba3857f5543e1e580-1724797632039-02719-_mMMfnwo&tt=MG&aff_fsk=_mMMfnwo&aff_platform=default&sk=_mMMfnwo&aff_trace_key=e42d3eefa5d8453ba3857f5543e1e580-1724797632039-02719-_mMMfnwo&shareId=21595548853&businessType=ProductDetail&platform=AE&terminal_id=bbfedbc90fe1413797dcc889367fef32&afSmartRedirect=y](url)
![IMG_8622](https://github.com/user-attachments/assets/5669773e-7751-4d1d-8c78-b09b9017764d)
![IMG_8623](https://github.com/user-attachments/assets/f219bfe9-1d74-4f03-810b-74e11649a938)
![IMG_8624](https://github.com/user-attachments/assets/cbe26b35-d0e3-417f-9b3f-5c943f0c66ae)
![IMG_8625](https://github.com/user-attachments/assets/fbc00fd0-75fe-4603-9b68-ab0c8354da66)
![IMG_8621](https://github.com/user-attachments/assets/33293a62-2e3a-47d1-b1d2-f1acf34a4f0a)
![RenderedImage](https://github.com/user-attachments/assets/e0d1552e-c6db-474b-a51f-006eaae7830a)

**Comment by lewisxhe** [comment]
The A7670G does not have a built-in GPS modem, regardless of whether the motherboard contains a GPS connector. 
If the order includes GPS, then it belongs to the external GPS module program.

**Comment by embedded-systems-lol** [comment]
okay I flashed GPSShield example and I am getting this in serial monitor 
is that okay ???? why I aint getting location ?? :(

`This sketch is only suitable for boards without GPS function inside the modem, such as A7670G
Works only with externally mounted GPS modules. If the purchased board includes a GPS extension module it will work, otherwise this sketch will have no effect
If the purchased modem supports GPS functionality, please use examples/TinyGSM_Net_GNSS
Location: INVALID  Date/Time: INVALID 09:50:40.00
Location: INVALID  Date/Time: INVALID 09:50:40.00
Location: INVALID  Date/Time: 8/29/2024 09:50:40.00
Location: INVALID  Date/Time: 8/29/2024 09:50:40.00
Location: INVALID  Date/Time: 8/29/2024 09:50:40.00
Location: INVALID  Date/Time: 8/29/2024 09:50:40.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:41.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:42.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:43.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:44.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:45.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:46.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:47.00
Location: INVALID  Date/Time: 8/29/2024 09:50:48.00
Location: INVALID  Date/Time: 8/29/2024 09:50:48.00 `

**Comment by lewisxhe** [comment]
GPS positioning must be in an area with visible sky, not indoors

**Comment by embedded-systems-lol** [comment]
Great !! it works now, thanks man
