### ISSUE TITLE
DeepSleep problem

### ISSUE THREAD

**Issue by Architect8** [Xinyuan-LilyGO/LilyGO-T-A76XX#134]
**T-SIM7670E - ver 1.2**

I want to put the ESP32 to sleep for 600 seconds. Additionally, while the ESP is sleeping, I want to be able to wake it up using GPIO39 or GPIO36 because they are not connected to any additional pins. Unfortunately, if I connect any wire or button leg to the pin without connecting the other side to GND or VCC, the device immediately resets—what am I doing wrong?

```
void setup(){  
  pinMode (39, INPUT_PULLDOWN);
  Serial.begin(115200);


  //Go to sleep now
  Serial.println("Going to sleep now");  
  esp_sleep_enable_ext0_wakeup(GPIO_NUM_39,1);
  esp_sleep_enable_timer_wakeup(600 * 1000000);  // 10min
  esp_deep_sleep_start();  
}

void loop(){
  //This is not going to be called
}
```

**Comment by lewisxhe** [comment]
There is no T-SIM7670E version. You should be talking about the ESP32 version of A7670E.

If it is the ESP32 version, you must add external pull-up resistors to use GPIOs above GPIO33 as inputs, because these GPIOs do not have internal pull-down and pull-up functions.
