### ISSUE TITLE
ArduinoIDE compilation error

### ISSUE THREAD

**Issue by Jvf01** [Xinyuan-LilyGO/LilyGO-T-A76XX#136]
I recently bought the board 
 LILLYGO TTGO A7670G/E/SA R2 4G with gps.
 I use ArduinoIDE and get the identification  of the plate to be : LillyGo T-Display 

 I've selected the board as:
 LillyGo T-Display
 ESP32 Dev
 ESP32S3
 and, when making the compilation of the code SendSMS.ino I get the error: 

 In file included from D\Arduino\SendSMS\SendSMS.ino:10:
 D:\Arduino\SendSMS\utilities.h:233:2: error: #error "Use ArduinoIDE, please open the macro definition matching to the board above <utilities.h>"
    233 |  #error "Use ArduinoIDE, please open the macro definition corresponding to the board above <utilities.h>"
        |   ^~~~~
 In file included from D:\Arduino\SendSMS\SendSMS.ino:24:
 D:\Arduino\SendSMS/TinyGsmClient.h:137:2: error: #error "Please defines GSM modem model"
    137 |  #error "Please Define GSM Modem Model"
        |   ^~~~~
 exit status 1 

 Compilation Error: #error "Use ArduinoIDE, please open the macro definition matching to the board above <utilities.h>" 

 How to solve? 

 Thanks

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/128
