### ISSUE TITLE
course data returns nothing

### ISSUE THREAD

**Issue by katoury** [Xinyuan-LilyGO/LilyGO-T-A76XX#139]
Hi,
Because I need to mention the course in my code,  I have tried "SendLocationFromSMS_Use_TinyGPS.ino" example with adding "course", but it displays nothing but "course:0.00".
course2 = gps.course.deg();
Any idea to get that data ?
Thanks

**Comment by lewisxhe** [comment]
I don't have this problem. When I can't get it at the beginning, it will remain at 0 until I get it.
![image](https://github.com/user-attachments/assets/37456628-d591-44e2-8133-1b647590dba9)

**Comment by katoury** [comment]
@lewisxhe Hi, it seems the picture you sent back is not from the code I mentioned. Here the result of "SendLocationFromSMS_Use_TinyGPS.ino"
09:24:54.931 - MESSAGE: Longitude: -0.222170 Latitude:43.401108
09:24:54.931 -> UTC Date:2024/9/13
09:24:54.931 →> UTC Time:7:24:54
09:24:54.931 → Speed: 163.00Km/H
09:24:54.931 →> course: 0.00
09:24:54.931 ->
09:24:55.623 → Send sms message OK

the code I added :
        double course2 = gps.course.deg();
         ...        
        msg_str += "course:";
        msg_str += String(course2);

**Comment by lewisxhe** [comment]
If you want the heading, then you should add some judgment and send the SMS only after getting the heading

**Comment by katoury** [comment]
What do you mean by "then you should add some judgment " ??

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/d65f1195-343b-433c-84c8-76167824ef2a)

**Comment by katoury** [comment]
Ok I did it.. so I have to check what I have done wrong... I will be back to tell you if it works or not
