### ISSUE TITLE
A7670e battery recharge

### ISSUE THREAD

**Issue by Jvf01** [Xinyuan-LilyGO/LilyGO-T-A76XX#145]
Good morning, 
I have the a7670e board and I need to know how the 18650 battery recharges.  Does USB-C power charge the battery?
Thank you

**Comment by Jvf01** [comment]
Thank you for your information.
Can you post a kink for the homepage because i can't find the home with the instructions you refer.

**Comment by Jvf01** [comment]
"....post a link..."

**Comment by lewisxhe** [comment]
https://www.lilygo.cc/products/t-sim-a7670e?_pos=1&_sid=1f6a77a6b&_ss=r&variant=42534734495925
