### ISSUE TITLE
Dubt about schematic on USB-C Connector

### ISSUE THREAD

**Issue by alexlopez2612** [Xinyuan-LilyGO/LilyGO-T-A76XX#146]
Hello
I have a ESP32 with A7640G board and I'm studiying the schematic to learn how the board works. By the way, the board works really good.
So, I want to learn how the USB-C connector is connected to the ESP32 uart. And when I see the part of the U11 (Typec) I see that pin A5 is on network CC1, and also I see that B8 is on CC1 network too. Why is this?? Is that correct or is a error on the schematic?
As I see on the connector documentation, SBU2 (B8 pin) it's for low speed signals and I don's understand this connection.
This is the image of what I'm seeing
![image](https://github.com/user-attachments/assets/ab2d20f9-f7c2-4a88-8144-e3d49e13c68d)

Another questions about this U11 are:
- pin B5, In the shematic text says VCONN, but I see that B5 is CC2 on the USB-C documentation. Why is that?
- SUB1 pin, really means "SBU1", right?

Maybe I'm using a old version of the schematic? I'm studing the T-7670X v1.4 and v1.1 and is the same.

Thank you!

Best regards

**Comment by lewisxhe** [comment]
Looks like this is wrong, I'll check with the guy who made this board after the holidays

**Comment by alexlopez2612** [comment]
> Looks like this is wrong, I'll check with the guy who made this board after the holidays

Hello lewisxhe

Oh! I thought that It was me that I'm starting to study this kind of boards, that are very advance for me.
I'm studiying all this schematic. If I see something wrong, it's ok ask this things over here?

Thanks and best regards!

**Comment by lewisxhe** [comment]
Of course, if I see it I'll answer you.
