### ISSUE TITLE
AT+CBC SIMCom modem supply voltage

### ISSUE THREAD

**Issue by kgmuzungu** [Xinyuan-LilyGO/LilyGO-T-A76XX#147]
@lewisxhe on my board it is resulting in 0.013V .... can you check? all supply pins of the modem's really connected?

**Comment by lewisxhe** [comment]
Please see the schematic diagram, this modem ADC is not connected to any circuit and has no function.

**Comment by kgmuzungu** [comment]
There are commands AT+CADC and AT+CADC2 in chapter 11 to read the ADCs. AT+CBC should read the supply voltage.

**Comment by lewisxhe** [comment]
This is a software definition. There is no actual hardware circuit connected to the modem's ADC pin, so it is invalid. You can only use the https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/tree/main/examples/ReadBattery sketch to read the battery voltage.

**Comment by kgmuzungu** [comment]
The A7670E has one ADC pin. It can be read with AT+CADC. It is not connected as you wrote. 

I am referring to the command AT+CBC in this issue. It reads the VBAT voltage, the chips supply voltage. This is N O T the ADC pin! On my board it reads 0.013V. Something is not right. Check on your boards.

**Comment by lewisxhe** [comment]
OK. I didn't see you said AT+CBC, I only saw AT+CADC in the front. Report the version you use, I will test it and report to SIMCOM

**Comment by kgmuzungu** [comment]
pls find all data about my firmware and model [here, issue 117](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/117)

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/ba3d2858-f3d0-43f6-9d3d-78935dfc78a0)
![image](https://github.com/user-attachments/assets/a395cbdb-7dc0-4a25-8c34-43810bfd4e34)
It has been confirmed that the conditions obtained by AT+CBC are not met, so 0 is returned.

**Comment by kgmuzungu** [comment]
The SIMCom documantations are so poorly written 😢 It might be as you say. But there is no reference that AT+CBC reads the ADC pin. 

Can you provide the source document you are citing?

BTW What does 'perfom partial external pressure' mean?
