### ISSUE TITLE
A7670E module store the same SMS twice when only one is sent

### ISSUE THREAD

**Issue by jpcasta** [Xinyuan-LilyGO/LilyGO-T-A76XX#155]
Hello,

When I send 1 SMS to the A7670E module, it stores it twice in 2 different storage entries:
Ex:
18:37:57.205 -> 
18:37:57.205 -> +CMTI: "SM",3
18:37:57.642 -> 
18:37:57.681 -> +CMTI: "SM",4

If I change the value how it receives new messages using the following command:
18:38:12.942 -> AT+CNMI=2,2,0,0,0
18:38:12.942 -> OK
Then it still receiving the message twice while I sent it only once:
Ex:
18:38:27.654 -> +CMT: "+336xxxxxxxx","","24/10/07,18:38:27+8"
18:38:27.698 -> Test SMS 
18:38:28.199 -> 
18:38:28.199 -> +CMT: "+336xxxxxxxx","","24/10/07,18:38:27+8"
18:38:28.243 -> Test SMS 

Why does this problem occurs?
I would like to receive only 1 SMS when I send 1.

Thanks
Regards

**Comment by lewisxhe** [comment]
Please provide the specific version of the module, attach the label on the modem, and the response message of AT+SIMCOMATI

**Comment by jpcasta** [comment]
1- Specific version of the module:
Do you mean the version of the board?
If it is the case it is: 
2022-7-18
V1.2

2-Label on the modem:
A7670E

3-Information returned by AT+SIMCOMATI
06:56:26.219 -> Manufacturer: INCORPORATED
06:56:26.251 -> Model: A7670E-LASE
06:56:26.251 -> Revision: A011B12A7670M7
06:56:26.283 -> A7670M7_B12V02_220613
06:56:26.315 -> QCN:
06:56:26.315 -> IMEI: 860470062753011
06:56:26.347 -> MEID:
06:56:26.347 -> +GCAP: +CGSM,+FCLASS,+DS
06:56:26.393 -> DeviceInfo:
06:56:26.393 -> 
06:56:26.393 -> OK

Thanks

**Comment by lewisxhe** [comment]
Also provide the label on the modem, need to determine the hardware version

**Comment by jpcasta** [comment]
Sorry, I do not understand what you mean by the label on the modem.
Are they the P/N and the SN values?
Thanks

**Comment by lewisxhe** [comment]
PN Number

**Comment by jpcasta** [comment]
P/N: S2-109ZT-Z313W

**Comment by lewisxhe** [comment]
Do a simple test and send a text message with only a few characters to see if it will be received twice.

**Comment by jpcasta** [comment]
It is received twice even when I send a SMS with 1 letter.
Thanks

**Comment by lewisxhe** [comment]
Please follow the documentation and video to upgrade the modem to the latest firmware, and then use the capture log to provide the log to SIMCOM for analysis.
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/docs/update_fw.md
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/docs/capture_log.md

**Comment by jpcasta** [comment]
OK but following weather issues here, it could take some days before I do it.
I will let you know as soon as I have time to do it.
Thanks

**Comment by jpcasta** [comment]
Hello,

I looked at the procedure and the video to upgrade the firmware but before performing the upgarde, I have some questions regarding the version of the available firmware file.

When I run the AT+SIMCOMATI command I get the following result:

Manufacturer: INCORPORATED
Model: A7670E-LASE
Revision: A011B12A7670M7
A7670M7_B12V02_220613
QCN:
IMEI: 860470062753011
MEID:
+GCAP: +CGSM,+FCLASS,+DS
DeviceInfo:

The Revision value is: A011B12A7670M7
According the video that means the version of the installed firmware is B12.

However in the A124B01A7670M7_A7670E-LASE_V101240627-latest.rar file provided on github for the A7670E-LASE (No GPS) model the zip file I should use for the upgrade is: A124B01V01A7670M7_A7670E-LASE_V101240627.zip
But according the video the version of this firmware would be B01.

Normally I should read a version number greater than B12?
AM I wrong reading the firmware version?

Do I need to use this provided file to upgrade the modem firmware or is there another file?

Thanks

**Comment by lewisxhe** [comment]
This is a new version baseband, so it starts from B01, but it has the prefix A124

**Comment by lewisxhe** [comment]
The IMEI may be lost due to firmware update. The IMEI is on the label of the modem. Send AT+SIMEI=IMEI number to reset it.

**Comment by jpcasta** [comment]
Ok Thanks a lot, it works again!!
The issue is solved.

Thanks for your help
Regards

**Comment by toupetlu** [comment]
Hello

I have the same problem (the A7670E module store the same SMS twice when only one is sent). So I would like to apply the proposal : install new firmware. But I work on win11 and in the video (and tutorial) only a diectory "Windows 10" is proposed for drivers. How o proceed for Win11?

thanks
