### ISSUE TITLE
getGPS() fails because CGNSSINFO does not contain fixMode integer

### ISSUE THREAD

**Issue by NeariX67** [Xinyuan-LilyGO/LilyGO-T-A76XX#157]
My A7670E-FASE (Rev. A7670M7_V1.11.1)

simplified code with AT command dump enabled:
```cpp
[...]
modem.enableGPS();
modem.setGPSMode(3);
[...]
if (modem.getGPS( [...] )) {
  Serial.println("GPS OK");
}
else {
  Serial.println("No GPS data available");
}
```

Console output:
```
AT+CGNSSINFO

+CGNSSINFO: ,,,,,52.XXXXXXX,N,13.XXXXXXX,E,,112414.00,75.9,,,,,,09

OK
No GPS data available
```

The modem clearly returns (accurate) GPS Data, but `getGPS()` still fails because the fixMode integer (value before first comma) is missing.

A firmware upgrade would not be a viable solution.

**Comment by lewisxhe** [comment]
This is because the data obtained is not confirmed to have been repaired. Please refer to the manual. This has nothing to do with the firmware upgrade. Each board is tested before leaving the factory.
![image](https://github.com/user-attachments/assets/861a47f4-ca97-4b49-a7c8-8a56a95c3799)
