### ISSUE TITLE
A7670E gets a dry spell in connecting to GPRS/LTE

### ISSUE THREAD

**Issue by djseban** [Xinyuan-LilyGO/LilyGO-T-A76XX#159]
Hey there, recently I started a little project. I started out with connecting with a SIM to the network. Thing is sometimes the device gets a streak where it connects to the network  as soon as it boots, but then randomly it won't connect at all and continue to do so. During troubleshooting I discovered that switching to a SIM-card that was recently in phone fixes a problem - I turn off the LilyGO, switch the SIM-card and magically it works, but when I restart it won't connect again. What might be a culprit?

**Comment by lewisxhe** [comment]
1. How to restart?
2. Is the LTE antenna connected to the correct position?
3. What is returned when sending **AT+CGREG?** and **AT+CSQ** queries when unable to connect to the network?

**Comment by kgmuzungu** [comment]
My experience is to repeat the above commands until it eventually connects. My connects within 30s but mostly quicker. Also get the latest firmware, the old frimware versions are buggy
