### ISSUE TITLE
A7670G - Built-in Led

### ISSUE THREAD

**Issue by Mike2573** [Xinyuan-LilyGO/LilyGO-T-A76XX#164]
Good afternoon,
I a recently got the model a7670g and i want to know if it has a way to control the built-in led (like the status or net ligth) for a communication purpouse.

Thanks.

**Comment by lewisxhe** [comment]
A7670G cannot control the network status light and operation status light, you need to connect an external LED to achieve the purpose

**Comment by Mike2573** [comment]
Hi lewisxhe,

Thank you very much for your prompt response regarding the issue.
