### ISSUE TITLE
individuare il pin led  LILYGO T-SIM7670G-S3 ESP32-S3 4G

### ISSUE THREAD

**Issue by PIERLUIGI1983** [Xinyuan-LilyGO/LilyGO-T-A76XX#166]
salve, ho acquistato diverse schede  t-sim7672g-v1.0 non riesco a trovare i pin dei led a bordo della scheda e quello della batteria,  vi sarei grato se mi potreste indicare quali sono. grazie

**Comment by lewisxhe** [comment]
There is no controllable LED light. You need an external LED 
What battery pins do you mean?

**Comment by PIERLUIGI1983** [comment]
avendo la scheda a boro diversi led pensavo che almeno uno era gestibile.. non è un problema.. grazie per la risposta.
