### ISSUE TITLE
gps and gsm not working 

### ISSUE THREAD

**Issue by toneshoo** [Xinyuan-LilyGO/LilyGO-T-A76XX#169]
when i first pluged in the device the power led (blue) was on and there was 2 other led (red) i belive for gsm and gps 
once i uploaded the firmware from github and started working on it using platform , io the problem started 
the gps and the gsm dont even blink anymore and can be seen 
i tried to change the wire reset etc nothing worked 
also there is a problem with the baudrate i keep getting random raw data whenever i upload anycode 
it compiles well but then the terminal shows !!!!#($#J$ somthing like this
i would love any help i can get on these issues

**Comment by lewisxhe** [comment]
Show this? Can you give me a full screenshot? I've never seen this error before, and I don't know which software this is from
![image](https://github.com/user-attachments/assets/d21fc436-ad71-4782-8a9b-89551984b11b)

**Comment by toneshoo** [comment]
![WhatsApp Image 2024-10-27 at 10 19 44 PM](https://github.com/user-attachments/assets/0502beca-ef17-44cf-b399-40629a543dd7)
i tried to change the baudrate but samething 
also the 2 led are not blinking

**Comment by lewisxhe** [comment]
Monitor baud rate is 9600, change sketch baud rate to 9600 or set monitor to 115200
![image](https://github.com/user-attachments/assets/3e9f6976-a8b6-4e96-b691-1bf1a771ce6b)

**Comment by toneshoo** [comment]
![image](https://github.com/user-attachments/assets/58773dca-6455-4166-bee5-111593c802d5)
alright one problem out of the way 
but still the gps and gsm led are not on and i get this

**Comment by lewisxhe** [comment]
You need SIM-HAT hardware support to run. The examples above all need SIM-HAT hardware support. Please run the minimum ATDebug to test and read the README first.

**Comment by toneshoo** [comment]
this is kind of my first time here 
could you explain more ?

**Comment by lewisxhe** [comment]
All examples with SIMhat in their names require the support of this hardware to run https://www.lilygo.cc/products/lilygo%C2%AE-t-simhat-can-rs485-relay-5v

README explains which examples can be used and which cannot

**Comment by toneshoo** [comment]
i saw many videos on youtube that connected a wifi and gps to the same excat model i use which is a7670e esp32 wroover e 
if i cant use these libaraies how should i proced?

**Comment by lewisxhe** [comment]
What do you mean? I don't understand what you mean?

**Comment by toneshoo** [comment]
before i decided to buy this model which is A7670E  
i checked some youtube videos to make sure it can work without any extra hardware
but if the examples above require some extra hardware 
can you help me find examples for the board itself alone ?

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/8bf86192-1ae6-4e93-a1fb-e38cee53626c)

**Comment by toneshoo** [comment]
hmmmmmm wait so in order to be able to use gsm and gps i need to buy the extra hardware ??

**Comment by lewisxhe** [comment]
Well, to use GSM and GPS you only need to buy A7670. SIM-HAT is a separate additional hardware, you can exclude it completely, I just want to tell you that SIMHAT*** example requires additional hardware support, understand? I think I made it clear.

**Comment by toneshoo** [comment]
yeah i get it now
what tuturial do i follow to start the gps and gsm 
right now there leds are off

**Comment by lewisxhe** [comment]
ATDebug

**Comment by toneshoo** [comment]
done that already 
every time i check the serial moniter when uploading any code i always get Failed to find INA219 1 chip in

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/a4aef6e8a0c768eef6ada97d62b5747b5a840c08/platformio.ini#L44
