### ISSUE TITLE
LILYGO T-A7670E No LED when powered by 18650 battery

### ISSUE THREAD

**Issue by Harbakk** [Xinyuan-LilyGO/LilyGO-T-A76XX#170]
My board lights up the blue led lights when I power the board with USB and solar power. If I power the board with 18650 4,2v battery the LED's wont turn on. I've checked and see that the board delivers 3,3v on both sides of the solder pads. Is it normal that the LED should not light up when powering by Battery?

**Comment by lewisxhe** [comment]
The blue light will only light up when charging, not when powered by battery.
