### ISSUE TITLE
T-A7670X wont use esp32 wifi module in example code

### ISSUE THREAD

**Issue by cullenoi** [Xinyuan-LilyGO/LilyGO-T-A76XX#173]
Hi all, I just recieved the lilyGo T-A7670E a few days ago and want to use it for a project, for ease of development I first wanted to  devlop my project on using the esp32's wifi then when I deploy it use the LTE connection. To get comfortable with the lilyGo codebase I tried to run the httpClient and the httpsClient, both of which would not run with wifi being set to true. 

When I checked the code it is because the [script](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/9ec4fc820926d18fdf58de9941dc5cb4092d0c95/examples/HttpClient/HttpClient.ino#L46) checks  if the gsm modem has wifi capabilities. 

A bit of digging led me to the  `TinyGsmClientA7670.h` header file where TinyGsmWifi is not included. 

When I try to include it to the library to the class I get the following error: 
```call to 'TinyGsmWifi<TinyGsmA7670>::networkConnectImpl' declared with attribute error: Not implemented``` 
the errror propogates at `TinyGsmWifi.tpp` 

I'm assuming this is definitely an  issue on my end due to lack of experience,  but the lilyGo T-a7670X's do have esp32 chips so this should be included in its headerfile? Any advice on how to resolve this would be great.(even if the resolution is me being silly!)

Kind Regards

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/fbb376d6-42ca-4bbb-8ff0-69085c12e5ca)
