### ISSUE TITLE
ATdebug.ino Example not working 

### ISSUE THREAD

**Issue by Kylektt** [Xinyuan-LilyGO/LilyGO-T-A76XX#174]
Hi, I have been working on Platformio previously and I need to do the firmware upgrade, so I download the Arduino IDE to follow the step here:
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/docs/update_fw.md

My first step is to upload the ATDebug_sketch

However, I cannot enter AT message after I upload the ATDebug_sketch.

Could anyone give me some idea? I will be very grateful!

![image](https://github.com/user-attachments/assets/b77fd0eb-5584-487e-8189-70523ee37bad)

![image](https://github.com/user-attachments/assets/a4019c0e-9b62-4d42-b358-c7399330ea0c)
![image](https://github.com/user-attachments/assets/48c4a73f-6cc0-4ebc-9992-d9904e9a691f)

![image](https://github.com/user-attachments/assets/7bd08254-5a95-44f8-b45c-78b0747e80cc)

**Comment by lewisxhe** [comment]
Is the correct board selected in utilities.h?
