### ISSUE TITLE
FalshTool Cannot detect the the COM Port

### ISSUE THREAD

**Issue by Kylektt** [Xinyuan-LilyGO/LilyGO-T-A76XX#175]
I think I'm experiencing the similar problem with:
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/122#issuecomment-2298353188

![image](https://github.com/user-attachments/assets/ca332fac-4714-4376-915b-c7820a352b31)

I can detect the ports on Device Manager, and also download the usb drivers followed by the video:
![image](https://github.com/user-attachments/assets/27f412c6-e229-4702-99f0-669d91c92dcb)

It mentioned "The best drivers for your device are already installed", however when it comes to the flash tool, all the ports are considered as the external port and not able to choose.

Thanks for your time to review this issue.

**Comment by lewisxhe** [comment]
Please note that you need to hold down the boot button next to the modem and then power it on. This will only work within a few seconds of the modem being powered on.
