### ISSUE TITLE
Availability of AGPS on T-A7670E 

### ISSUE THREAD

**Issue by OCMTemp** [Xinyuan-LilyGO/LilyGO-T-A76XX#176]
On my T-A7670E, I tried to use the AGPS example:

https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/tree/main/examples/GPS_Acceleration

But I get the error:

`'TinyGsm' {aka 'class TinyGsmA7670'} has no member named 'enableAGPS'; did you mean 'enableGPS'?`

I know the T-A7670G does not support GPS Acceleration. But does the T-A7670E? If it does, then what could be the cause of the error?

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/4ee1e5ce510d8f7bfd9e9c08052e0434099df35d/README.md?plain=1#L7

**Comment by OCMTemp** [comment]
Thanks! That solved the problem and made obtaining a lock significantly faster.
