### ISSUE TITLE
How to update firmware for T-Call-A7670X-V1-0?

### ISSUE THREAD

**Issue by Tsury** [Xinyuan-LilyGO/LilyGO-T-A76XX#180]
Hello.

I have `T-Call-A7670X-V1-0`.
I'm trying to use it without connecting anything in addition (no other devices connected, including no mic and no speaker).

I'm experiencing freezes all the time, just trying to run the `ATdebug` example.
It would most of the time just freeze on startup, after this part:

```
Trying baud rate 115200
Modem responded at rate:115200
***********************************************************
 You can now send AT commands
 Enter "AT" (without quotes), and you should see "OK"
 If it doesn't work, select "Both NL & CR" in Serial Monitor
 DISCLAIMER: Entering AT commands without knowing what they do
 can have undesired consiquinces...
***********************************************************
```

Sometimes it would work for a while and then freeze after 30secs, 2mins etc.

I want to update its firmware.
I executed `AT+SIMCOMATI` and received:

```
Model: A7670E-FASE
Revision: A110B01A7670M7_F
A7670M7_B01V01_240105
```

From here I'm very confused how to continue - I've seen the video recording and read the guide, but it seems to all be related to the other T-Call, the one that has a MicroUSB connection for firmware update. Mine doesn't - mine only has a USB C connection.

This is the device I have:
![image](https://github.com/user-attachments/assets/f7413923-b6e6-4105-bd22-ee93a19760f9)

How do I put it into modem flashing mode?

I'm stuck at `getting serial devices list...` when I try to use MADL.
I'm trying to flash this firmware: `A011B07V01A7670M7_F_A7670E-FASE_CD_V101230711`.

I see that there's a `7670_BOOT` button, it must be related, but I can't seem to figure out.

Please guide me in the right direction so I'll be able to update the firmware, thanks.

A side question:
What is the role of the leds?
I guess the green led on the back is for power, but what is the led near the `RST` button? And what is the led near the `7670_BOOT` button?

Currently for me, the power is constant green, the `7670_BOOT` is constant red abd the `RST` is blinking red.

**Comment by lewisxhe** [comment]
T-Call requires a USB cable, which is then connected as shown below, and can then be plugged into a computer for upgrades. The rest of the board is the same as other boards.

![image](https://github.com/user-attachments/assets/2aedce38-274b-4f86-b4ac-cf6099241dde)

Also, what do you mean by frozen? No response?

**Comment by lewisxhe** [comment]
If there are no problems during use, do not update the firmware. There is no update instruction. SIMCOM does not provide this.

If the indicator light is off when freezing, it is likely caused by insufficient voltage. You need to test whether the input has reached 5V.

**Comment by Tsury** [comment]
Got it, appreciate the help and fast response. I really love your hardware, thank you.
