### ISSUE TITLE
Firmware installation for Windows11 

### ISSUE THREAD

**Issue by toupetlu** [Xinyuan-LilyGO/LilyGO-T-A76XX#185]
Hello

I have the same problem that the closed issue #155  (the A7670E module store the same SMS twice when only one is sent). So I would like to apply the proposal : install new firmware. But I work on win11 and in the video (and tutorial) only a diectory "Windows 10" is proposed for drivers. How to proceed for Win11?

thanks

**Comment by lewisxhe** [comment]
The drivers for win11 and win10 are the same, and the computer I recorded the video on is also win11

**Comment by toupetlu** [comment]
OK, i will do the firmware update in following days.
