### ISSUE TITLE
Can we use the speaker connected to T-Call-A7670X for other usages?

### ISSUE THREAD

**Issue by Tsury** [Xinyuan-LilyGO/LilyGO-T-A76XX#189]
I soldered a speaker to the SPK+/- and it works great for calls.

When not in a call, I would like to use the speaker for other things, like text-to-speech, etc...

Is it possible? If so, how to achieve it? Thanks.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/datasheet/A76XX/A76XX_Series_AT_Command_Manual_V1.12.pdf

![image](https://github.com/user-attachments/assets/58a95cfb-1427-45fc-9f27-1ad100a627b7)

**Comment by Tsury** [comment]
Thanks, but what if I want to use it for anything else? Play a sound file etc? Is there a possibility?

**Comment by Tsury** [comment]
I will check the manual then, thanks.

**Comment by Tsury** [comment]
Thanks @lewisxhe 
Do you think it's possible to also play an audio file? I saw something in the manual but wasn't able to make it work, maybe you could?

Thanks in advanced and appreciate the help!

**Comment by lewisxhe** [comment]
It has not been implemented yet. To play an audio file, you need to write the audio into fs before you can play it. I have not implemented this function, but it may be added later.

**Comment by Tsury** [comment]
Oh wow, I see.

Well, I would _greatly_ appreciate if this was implemented - it really enhances the usability of the device and will spare me from connecting multiple speakers.

Thanks in any case of course.

**Comment by DomoMKT** [comment]
you can easily convert your text into high-quality speech with extremely low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com).

**Comment by Tsury** [comment]
Hey, was there any progress with this? Can I somehow help test/develop it? I really need this, thanks!

**Comment by lewisxhe** [comment]
I haven't implemented this function yet, but I can find time to test its possibility. First of all, I would like to state that this method will take up the internal space of the modem. There is only 4MB of space inside the A7670, so it cannot play audio files that are too large.

**Comment by lewisxhe** [comment]
Already added, for detailed description, please refer to the AT command manual

**Comment by Tsury** [comment]
Oh wow thank you so much, going to test it now. Yeah I don't need a lot, just some indications, basic short mono sounds, low quality.

**Comment by Tsury** [comment]
@lewisxhe It works amazingly, thank you so much! Going to order 3 more now that I know I can finish the project.
