### ISSUE TITLE
Broken link for schematic T-SIM767XG-S3

### ISSUE THREAD

**Issue by david-biro** [Xinyuan-LilyGO/LilyGO-T-A76XX#191]
The link at [https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/schematic/T-SIM7672-S3-V1.0.pdf](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/schematic/T-SIM7672-S3-V1.0.pdf)  is broken.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/schematic/T-SIM767X-S3-V1.0.pdf
