### ISSUE TITLE
utilities.h: No such file or directory

### ISSUE THREAD

**Issue by 23tom2323** [Xinyuan-LilyGO/LilyGO-T-A76XX#194]
Hello, I use VoiceCalls.ino but Arduino still needs utilities.h. Where can I get that?
LilyGO-T-A76XX/examples/VoiceCalls/VoiceCalls.ino

#####################################
C:\Users\xx\AppData\Local\Temp\.arduinoIDE-unsaved20241115-33160-g1trb8.ybsee\sketch_dec15a\sketch_dec15a.ino:15:10: fatal error: utilities.h: No such file or directory
   15 | #include "utilities.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: utilities.h: No such file or directory
#####################################

**Comment by ArthurTimmermans** [comment]
@23tom2323 Make sure it is in the same folder as your poject

If I check the repository, it is there
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/examples/VoiceCalls/utilities.h
