### ISSUE TITLE
AT+CGSN returns memory failure

### ISSUE THREAD

**Issue by ArthurTimmermans** [Xinyuan-LilyGO/LilyGO-T-A76XX#195]
Hello,

I wanted to report a bug on the A7670G latest firmware.
If you want to check the IMEI of the device, it returns a memory failure CME

`AT+CGSN`
`+CME ERROR: memory failure`

Also the ATI does not return an IMEI

`AT+SIMCOMATI`
`Manufacturer: SIMCOM INCORPORATED`
`Model: A7670G-LLSE`
`Revision: A124B01A7670M7`
`A7670M7_B01V01_240722`
`IMEI: `

![CleanShot 2024-12-15 at 16 14 27@2x](https://github.com/user-attachments/assets/b5107810-69d0-443f-8571-3bdb18d0d3cb)

**Comment by lewisxhe** [comment]
The IMEI may be lost when upgrading the firmware. You can use the

```bash
AT+SIMEI=867284064546817
```
command to restore it

**Comment by lewisxhe** [comment]
By the way, thanks for your reply to other issues.
