### ISSUE TITLE
Strange value from the GPS

### ISSUE THREAD

**Issue by peder2key** [Xinyuan-LilyGO/LilyGO-T-A76XX#29]
Hello

I am testing the gps and getting back strange Lat and Lot values: 

at:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.133333 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000
lat:-0.150000 lon:-0.000000

what is the unit? 

Best Regards

**Comment by LilyGO** [comment]
Hello. Did you buy the one with GPS? Which example did you use?

**Comment by peder2key** [comment]
Hello,

I bought this unit: https://www.aliexpress.com/item/1005003036514769.html?spm=a2g0o.order_list.order_list_main.156.1ca01802oLv0sw

I have tested this example: https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/examples/new_version/Arduino/TinyGSM_Net_GNSS/TinyGSM_Net_GNSS.ino

I have also tried to get the modem.getGPSraw() string also which gave me this result:

3,10,,00,00,5923.88109,N,01027.87128,E,091222,133005.00,67.9,2.319,,3.8,2.5,2.9

but the modem.getGPS(&lat, &lon) gives me: 
lat:-0.000000 lon:-0.000000

**Comment by LilyGO** [comment]
It is caused by different parameter positions

**Comment by miscawelo** [comment]
I bought the non GPS version and later connected an antenna I had laying around, but I can't power up the GPS, it erros out. Is there any difference between the two versions? Besides the included antenna

**Comment by LilyGO** [comment]
> hmm what does that mean?

[reference](https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/examples/new_version/Arduino/TinyGSM_Net_GNSS/TinyGSM_Net_GNSS.ino#L284)

**Comment by LilyGO** [comment]
> It's the difference without GPS. All other things

**Comment by LilyGO** [comment]
> I bought the non GPS version and later connected an antenna I had laying around, but I can't power up the GPS, it erros out. Is there any difference between the two versions? Besides the included antenna

It's the difference without GPS. All other things

**Comment by mikandrzej** [comment]
I also have issue with position of parameters. It seems that library has a bug - or maybe there should be command before using getGPS to change position of parameters...

**Comment by lewisxhe** [comment]
Are you running the previous sketch or the latest clone?
