### ISSUE TITLE
How to completely power off the modem?

### ISSUE THREAD

**Issue by laarlinn** [Xinyuan-LilyGO/LilyGO-T-A76XX#49]
Hi all, this might be a noob question,

but how to completely cut the power from the modem before going into deep sleep?

Currently I am sending the power off command to the modem, but as told in the examples, I should also use BAT_EN pin to make
sure the modem stays off. However I am not sure what to do.

Do I need a pull-down resistor to keep the pin low when in deep sleep?

Thanks in advance

**Comment by lewisxhe** [comment]
BAT_EN is kept low during sleep, no operation is required if it enters sleep.
