### ISSUE TITLE
Schematic v1.2

### ISSUE THREAD

**Issue by HDC67** [Xinyuan-LilyGO/LilyGO-T-A76XX#51]
Can you add the schematics for v1.2 to the repo please. 

Thanks

**Comment by lewisxhe** [comment]
V1.1 and V1.2 are just more ADC resistors, sorry I can't provide them now because the data has been lost.

**Comment by ShonkyCH** [comment]
I find that hard to believe that you have lost the design that you are selling. 

Please document it here then?

**Comment by qnixAVA** [comment]
Still don't have shematic for V1.2 ?

**Comment by ShonkyCH** [comment]
Nope

**Comment by ShonkyCH** [comment]
Nope

**Comment by neuralprocessing** [comment]
Could you please double check, that the DTR Pin No. 3 from SIM7670E is in V1.2 still connected to the ESP GPIO Pin No. 25?
The deep sleep method of driving ESP GPIO 25 HIGH to set DTR Pin high seems not to work properly. The wiring might have changed from V1.1 to V1.2.
