### ISSUE TITLE
Need schematic and datasheet for V1.3  2023-6-15

### ISSUE THREAD

**Issue by tewbc** [Xinyuan-LilyGO/LilyGO-T-A76XX#55]
I've got a new A7670G with GPS and cannot find any details for its version and also about small board near battery holder that may be the another GNSS receiver that cannot not use. Did anyone has some info?

**Comment by lewisxhe** [comment]
It is exactly the same as V1.1, just add the external GPS pad, and resistor divider.
A7670G must use an external GPS module to locate, otherwise the modem does not support GPS function

**Comment by tewbc** [comment]
Oh I see, Thank for replied.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by rgusso** [comment]
so the GNSS antena connector near the USB-C is useless?

**Comment by tewbc** [comment]
As he mentions it, yes for sure.
https://ibb.co/sQPtzCz
