### ISSUE TITLE
Example for MQTTS connection

### ISSUE THREAD

**Issue by caeb92** [Xinyuan-LilyGO/LilyGO-T-A76XX#63]
Following the examples  from the repository I have been able to establish an MQTT connection with rabbitMQ using port 1883 with user and password settings, i can publish and consume messages from topics without problem, but when trying to connect to hivemq cloud through the port 8883 with SSL the connection fails, 

Im using TinyGsmClient and PubSubClient for establish connections with MQTT brokers, i was reading the documentarion of [TinyGsmClient](https://github.com/vshymanskyy/TinyGSM#supported-boardsmodules) and says SSL/TLS(HTTPS) Are not yet supported on: Quectel modems, SIM 5360/5320/7100, SIM 7500/7600/7800.

I was wondering if there is an easy way to establish the connection or I must use AT commands?

**Comment by CyanoFresh** [comment]
also would like to get an example

**Comment by lewisxhe** [comment]
I have added an example of MQTTS
