### ISSUE TITLE
solar charge

### ISSUE THREAD

**Issue by rgusso** [Xinyuan-LilyGO/LilyGO-T-A76XX#64]
Hello, I'm attempting to charge an 18650 battery using a 6V, 15W solar panel. However, it seems to only reach approximately 3.5V in charge.The board is connected to the internet continuously, with no Bluetooth, consuming an estimated 150-200mAh.

[SUNYIMA 6V 15W](https://pt.aliexpress.com/item/1005005972931412.html)

![solar](https://github.com/Xinyuan-LilyGO/T-A7670X/assets/6697727/c3acccfa-4c3b-484f-8f60-3050627e6f40)

**Comment by HDC67** [comment]
How much power / current is the panel actually producing? Perhaps it's only just covering the 150-200mA needed to run the board.

Cheap solar panel ratings are often quite optimistic.
