### ISSUE TITLE
Receive sms/call

### ISSUE THREAD

**Issue by StergiosT0** [Xinyuan-LilyGO/LilyGO-T-A76XX#66]
Hello,
Is there any code example about receive call/sms?
Thanks

**Comment by HDC67** [comment]
TinyGSM is used in the examples so something like this should be a good enough example
https://randomnerdtutorials.com/esp32-sim800l-send-text-messages-sms/
and
https://forum.arduino.cc/t/can-somebody-help-me-to-how-read-the-received-sms-on-esp32-ttgo-t-call-using-arduino-ide/1157804/12
