### ISSUE TITLE
Request product information : T-A7670E/G/SA R2

### ISSUE THREAD

**Issue by boseonlee** [Xinyuan-LilyGO/LilyGO-T-A76XX#70]
I Request information on T-A7670E/G/SA R2 product.

I need two pieces of information, the details are shown in the picture below.

![image](https://github.com/Xinyuan-LilyGO/T-A7670X/assets/149124462/c9a86ee1-74cc-4aff-8af5-fa74c637cc88)

**Comment by lewisxhe** [comment]
I added the dwg and you can measure it yourself
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/dimensions/T-A7670X-V1.1.dwg
