### ISSUE TITLE
question about T-SIM A7670E

### ISSUE THREAD

**Issue by asat232** [Xinyuan-LilyGO/LilyGO-T-A76XX#71]
I need to make voice calls using microphone as input, is it possible? 
On the schematic are shown MIC+ and MIC-, but i dont see  them on pinout diagram. 
Can i connect microphone to some pads on the board, or on board is present built-in microphone?

**Comment by lewisxhe** [comment]
Yes, you need to connect the condenser microphone wires to MIC+, MIC-

**Comment by asat232** [comment]
looking the picture, as it seems to me MIC+/MIC- and SPK+/SPK- contacts on the side of the battery holder, close to its bottom on the right. Am i right?
(i dont have the board at the moment, just considering to order it and use it for my new project)

**Comment by lewisxhe** [comment]
> looking the picture, as it seems to me MIC+/MIC- and SPK+/SPK- contacts on the side of the battery holder, close to its bottom on the right. Am i right?
> (i dont have the board at the moment, just considering to order it and use it for my new project)

yes

**Comment by asat232** [comment]
thanks a lot
