### ISSUE TITLE
A7670G GPS AT+CGNSSPWR=1 ERROR

### ISSUE THREAD

**Issue by sylwesterm** [Xinyuan-LilyGO/LilyGO-T-A76XX#73]
I bought A7670G with attached GPS antenna. I tried several different examples but when call command AT+CGNSSPWR=1 it returns ERROR. I read somewhere that this device has no built in GPS. I tried two examples such GPSShield and GPSBuiltin. If this is the case that the A7670G doesn't have a GPS why the board has GNNS connector and attached GPS antenna??

**Comment by lewisxhe** [comment]
7670G does not have GPS function

**Comment by sylwesterm** [comment]
I ordered this part (see attached picture) It says it has GPS.
![chrome_LJYHYPAgw3](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/13168672/c9a73e70-e37c-42a9-bbfc-965578b1e920)
Why this board has GNSS connector and why it sold with GPS antenna??

**Comment by lewisxhe** [comment]
The GPs connector on the front of the motherboard is invalid, and the Gps module is located on the back of the board, next to the 18650 battery holder

**Comment by sylwesterm** [comment]
Can you show it?
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/13168672/12d99b76-83c8-41f8-b29b-d67eb0bb2f9e)

**Comment by lewisxhe** [comment]
See there https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/56#issuecomment-1672628977

**Comment by sylwesterm** [comment]
Thank you.
