### ISSUE TITLE
Does A7670G model with GPS support 0.96 Inch OLED? 

### ISSUE THREAD

**Issue by WEDOBROADCAST** [Xinyuan-LilyGO/LilyGO-T-A76XX#74]
Hi,

Can A7670G model with GPS support 0.96 Inch OLED as i saw the GPS module is being soldered at the board near the I2C pin.

Thanks

**Comment by lewisxhe** [comment]
No, GPS is already in use, so it cannot be configured as I2C

**Comment by WEDOBROADCAST** [comment]
Understood. Thank you so much for the info.
