### ISSUE TITLE
Firmware update instructions do not include or explain where to get the firmware image from

### ISSUE THREAD

**Issue by gitcnd** [Xinyuan-LilyGO/LilyGO-T-A76XX#78]
On this page:  https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/docs/update_fw.md

Step 5 has a screenshot of someone selecting a firmware .zip image to update with.

There is no explanation of where that comes from, and is is not included in the "A76XX_A79XX_MADL V1.13 Only for Update.rar" linked package.

Firmware update is needed, because the GPS has a critical bug in it: locations have leading zeros truncated from after the decimal point, and are missing their sign:   e.g.  -26.0043 gets reported as 26.43  ... which makes the GPS useless in most situations.

NOTE: I am talking about updating the firmware on the T-A7608SA GPS/LTE module, *not* the ESP32 firmware

**Comment by lewisxhe** [comment]
What version are you using now?
Please send AT+SIMCOMATI inquiry

**Comment by gitcnd** [comment]
I get this:-

```
CGSM,+FCLASS,+DS\r\nDeviceInfo:\r\n\r\nOK\r\n'
AT+SIMCOMATI
Manufacturer: INCORPORATED
Model: A7608SA-H
Revision: A50C4B08A7600M7
A7600M7_B08V02_220929
QCN:
IMEI: 862733060195479
MEID:
+GCAP: +CGSM,+FCLASS,+DS
DeviceInfo:

OK
```

by the way - I am writing an open-source micropython driver for this

**Comment by lewisxhe** [comment]
Hi @gitcnd 

The following upgrade files are only applicable to A7608SA-H, please do not flash other versions.
[Driver&Firmware](https://drive.google.com/drive/folders/1cswMz1PuQxm8pwRsA-oRj_DuzTK-cLqB?usp=drive_link)
[Recording](https://www.youtube.com/watch?v=GYEBoEavGzs)

**Comment by gitcnd** [comment]
Understood - thanks heaps !!
