### ISSUE TITLE
ESP resets when USB disconnects while battery installed and charged

### ISSUE THREAD

**Issue by FransOv** [Xinyuan-LilyGO/LilyGO-T-A76XX#85]
The T-A7608 (https://www.lilygo.cc/products/t-a7608e-h)is powered via usb and the installed battery is charged. When the battery voltage reaches 4V I switch off the usb power to protect the battery from overcharging. When the usb power is disconnected the brownout detector is triggered and the ESP resets. Sometimes, not always, there then occurs a second reset and the ESP enters download mode although nothing is connected to GPIO0.
```
Brownout detector was triggered

ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
ets Jul 29 2019 12:21:46

rst:0x10 (RTCWDT_RTC_RESET),boot:0x2 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_FEO_V2))
waiting for download
```

**Comment by Rikests** [comment]
This might be related to the other Brownout issue, where ESP32 brownouts when IO12 is pulled high to connect battery power to the modem.
You can try adding a 220uA or bigger cap on ESP32 power pins and see if that helps.

**Comment by FransOv** [comment]
I tried with 1000 μF and with 2200 μF capacitor on the 3V3 rail, but the ESP32 still resets. Soldered an external pull-up resistor to GPIO0 to prevent resetting into download firmware mode. Now I have only the problem of a reset about every 20 to 24 hours. I suppose I can accept that.

**Comment by lewisxhe** [comment]
It seems to be caused by unstable power supply. Excessive capacitance may cause the DC power-on current to be very large and may be destroyed. 220uF may be a better choice.

If GPIO0 is not used, there is no need for an external pull-up resistor, because GPIO0 defaults to an internal pull-up.

**Comment by pacmac** [comment]
I have the same problem, every time the modem is powered on it gets a brownout. I have fully charged 18650 3200mah battery and also supplying power via VBAT pin and a good quality power supply ever time the modem is powered on, from a powered off state, I get a brownout.

I added a 100uf cap and that made no difference, I see the comments above about 200uf, but this is obviously a design issue and right now the board is useless to me unless it can sleep and wake and power on and off the modem reliably.

**Comment by pacmac** [comment]
Yes this is a problem.

The power Pin must be set high at boot time, if you set it after boot you will get immediate brownout.

And this means that the modem must always be powered on when waking from deep sleep, this is a show stopper for me, that is just not viable.

I want to control when the modem comes on, it cannot come on every time after wakeup, that is totally impractical.

**Comment by pacmac** [comment]
Is there a solution to this ?

Whenever Power Pin is set high (GPIO12) the device brownouts no matter whether connected to battery or USB. Adding capacitors across the supply makes no difference at all.

At the moment I have 2 new boards and because of this they are unusable ??

Thanks

**Comment by lewisxhe** [comment]
@pacmac  Hi, Do you mean that if you set GPIO12 after startup, the power will be cut off immediately? Are you using the T-A7670 ESP32 version?

**Comment by lewisxhe** [comment]
There is no problem with my test here

**Comment by pacmac** [comment]
```
  #define BOARD                               "ESP32 Wrover Module"
  #define MON                                 Serial
  #define SIM                                 Serial1

  #define PWRKEY_PIN                          (4)
  #define MODEM_RESET_PIN                     (5)
  #define POW_PIN                             (12)
  #define MODEM_DTR_PIN                       (25)
  #define MODEM_TX_PIN                        (26)
  #define MODEM_RX_PIN                        (27)
  #define MODEM_RING_PIN                      (33)
  #define VBAT_PIN                            (35)

const int SER_BAUD =                          115200;

void setup() {
  
  // Serial Setup
  MON.begin(SER_BAUD);
  while(!MON){delay(100);} 
  MON.println("Serial Started");
  
  // SIM Serial
  SIM.begin(SER_BAUD, SERIAL_8N1, MODEM_RX_PIN, MODEM_TX_PIN);
  while(!SIM){delay(100);}

  delay(1000);
  pinMode(POW_PIN, OUTPUT);
  digitalWrite(POW_PIN,LOW);

}

void loop() {
  delay(2000);
  MON.println("Looping");
  digitalWrite(POW_PIN,HIGH);
}
```


```
Looping
Looping
Looping
Looping
Looping
Looping
xxxx�x�x�x���x��x�x��������x�x�x�xx�x���xLooping

Brownout detector was triggered

ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
```

**Comment by lewisxhe** [comment]
A7608 consumes more power than A7670. According to the log, it triggers esp32 low voltage reset.

Try the example I just uploaded and see if it has the same effect.

**Comment by pacmac** [comment]
what example ?

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/commit/38c88d4b0315e36ea0f2fd6dc8c92bcd43723498

**Comment by pacmac** [comment]
FYI I am not using TinyGSM, I find it much too bloated.

But when I define the board before the include it errors:

```
#define LILYGO_T_A7608X
#include "utilities.h"
#include <TinyGsmClient.h>
#include "Arduino.h"
```

```
In file included from /Users/pac/Documents/Arduino/PAC/Sketches/Lily_tests/T1.ino:22:
/Users/pac/Documents/Arduino/libraries/TinyGSM/src/TinyGsmClient.h:118:2: error: #error "Please define GSM modem model"
 #error "Please define GSM modem model"
```

**Comment by lewisxhe** [comment]
Define it here .
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/c22ed0ed1210a83b7ecea7d3f726b03e5bf0a812/examples/ModemPowerOff/utilities.h#L30

**Comment by pacmac** [comment]
why not just use a simple sketch like mine ?

**Comment by lewisxhe** [comment]
You are not using the fork version of TinyGSM, so the prompt is that the modem is not defined. The test method you used is correct. I will try it here too. Thank you for your cooperation

**Comment by lewisxhe** [comment]
This has nothing to do with the software. Did you connect the SIM card during the test?

**Comment by lewisxhe** [comment]
Is the SIM card normal? Can I access the network normally?

**Comment by pacmac** [comment]
Sim Card is installed, everything works, I can publish MQTT messages no problem, but every time I power on the modem I get a brownout.

I have tried with fully charged 18650 as well as 5A Good Quality Bench supply, I am confident that this is not an issue with my setup.

**Comment by pacmac** [comment]
I also have SIM7600 and have no problems with that, using same SIM card and power supply, this appears to be an issue with the board ?

**Comment by lewisxhe** [comment]
Please take a video and send it to the salesperson for after-sales processing. This problem cannot be solved from the software side

**Comment by pacmac** [comment]
so you cannot replicate this issue using my sketch ?

**Comment by lewisxhe** [comment]
Yes, I use the same sketch and there will be no power outage here.

**Comment by pacmac** [comment]
have you tried connecting using VBAT and use a USB Serial adapter on TX/RX instead of using the USB-C connector ?

That is how I am testing as when the unit is deployed it will be battery powered and not powered via USB

**Comment by pacmac** [comment]
This happens the first time that the GPIO12 is pulled high after power was reconnected or a new sketch uploaded.

The loop in my sketch crashes the device the first time it is called, after the brownout and device reboots itself, but after reboot the device continues to loop when setting GPIO12 low and high:

```
void loop() {
  delay(2000);
  MON.println("Looping");
  digitalWrite(POW_PIN,HIGH);
  delay(2000);
  digitalWrite(POW_PIN,LOW);
}

```

**Comment by pacmac** [comment]
Just to confirm, this problem does not happen when powered by USB.

But if powered using fully charged 3200mah 18650 @4.2v, or by supplying power via the VBAT pin using a 5A Bench Power Supply, then the brownouts happen.

Can you please test using the same power method rather than using USB-C to test

Thanks

**Comment by lewisxhe** [comment]
I will run the test tomorrow and let you know the result tomorrow

**Comment by pacmac** [comment]
Thanks, I just connected a super cap across VBAT and Ground and it makes no difference, every time it bownouts;

This is my revised loop:


```
void loop() {
  delay(20000);
  MON.println("Power On");
  digitalWrite(POW_PIN,HIGH);
  delay(20000);
  MON.println("Power Off");
  digitalWrite(POW_PIN,LOW);
}

```

```

Brownout detector was triggered

ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
Serial Started
Power On

Brownout detector was triggered

ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
Serial Started
Power On

```

**Comment by lewisxhe** [comment]
Yes, I have the same problem here. The only way to solve it is to remove the MOS tube in the picture below and short-circuit the two points of the connection.
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/22990954/4322f167-3e79-49af-b05c-4b0d354a763d)

**Comment by pacmac** [comment]
well at least yiu can now see the problem I have been trying to troubleshoot for the last 4 days !

What if I leave the mosfet there and just short out the pins instead so it is easy to reverse if necessary ?

**Comment by pacmac** [comment]
is that mod going to increase deep sleep standby current ?

**Comment by pacmac** [comment]
That appears to have solved the problem, but will it affect power consumption ?

**Comment by lewisxhe** [comment]
Deep sleep power consumption is approximately 240uA
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/22990954/001afc2d-7ea4-4e91-bfd1-137526ae1a8e)

**Comment by pacmac** [comment]
my deep sleep current has now doubled to 0.44ma

**Comment by pacmac** [comment]
That fix wont work as now the modem always powers on after Deep Sleep.

**Comment by lewisxhe** [comment]
Yes, I can confirm that after waking up from deep sleep, the modem starts automatically, I will give feedback to the designer who designed this PCB

**Comment by pacmac** [comment]
This is unworkable for anybody who requires long life on battery and who only enables the modem once in a while and not on every wakeup.

This is clearly a design defect and needs to be fixed with a hardware revision, I am not sure it can be fixed with a hack.

What is the process to get replacement boards when the issue is fixed with new hardware ?

Thanks for helping.

**Comment by lewisxhe** [comment]
I have found the problem. Please use this example to test, but the premise is that the two points of the MOS tube mentioned above must be short-circuited.
```
#include <Arduino.h>

#define uS_TO_S_FACTOR      1000000ULL  /* Conversion factor for micro seconds to seconds */
#define TIME_TO_SLEEP       30          /* Time ESP32 will go to sleep (in seconds) */

#define BOARD                               "ESP32 Wrover Module"
#define MON                                 Serial
#define SIM                                 Serial1

#define PWRKEY_PIN                          (4)
#define MODEM_RESET_PIN                     (5)
#define POW_PIN                             (12)
#define MODEM_DTR_PIN                       (25)
#define MODEM_TX_PIN                        (26)
#define MODEM_RX_PIN                        (27)
#define MODEM_RING_PIN                      (33)
#define VBAT_PIN                            (35)
#define MODEM_RESET_LEVEL                   HIGH

const int SER_BAUD =                          115200;

void setup()
{
    // Serial Setup
    MON.begin(SER_BAUD);
    while (!MON) {
        delay(100);
    }
    MON.println("Serial Started");

    // SIM Serial
    SIM.begin(SER_BAUD, SERIAL_8N1, MODEM_RX_PIN, MODEM_TX_PIN);
    while (!SIM) {
        delay(100);
    }

    if (esp_sleep_get_wakeup_cause() == ESP_SLEEP_WAKEUP_TIMER) {
        Serial.println("Wakeup timer");
        int i = 30;
        while (i > 0) {
            Serial.printf("Modem will start in %d seconds\n", i);
            Serial.flush();
            delay(1000);
            i--;
        }
        Serial.println("TurnON Modem!");
    }


    // Release reset GPIO hold
    gpio_hold_dis((gpio_num_t)MODEM_RESET_PIN);

    // Set modem reset pin ,reset modem
    // The module will also be started during reset.
    Serial.println("Set Reset Pin.");
    pinMode(MODEM_RESET_PIN, OUTPUT);
    digitalWrite(MODEM_RESET_PIN, !MODEM_RESET_LEVEL); delay(100);
    digitalWrite(MODEM_RESET_PIN, MODEM_RESET_LEVEL); delay(2600);
    digitalWrite(MODEM_RESET_PIN, !MODEM_RESET_LEVEL);


    Serial.println("Power on the modem");
    pinMode(PWRKEY_PIN, OUTPUT);
    digitalWrite(PWRKEY_PIN, LOW);
    delay(100);
    digitalWrite(PWRKEY_PIN, HIGH);
    //Ton >= 100 <= 500
    delay(300);
    digitalWrite(PWRKEY_PIN, LOW);


    delay(20000);

    // Power off modem
    Serial.println("Power off the modem");
    digitalWrite(PWRKEY_PIN, HIGH);
    delay(2000);
    digitalWrite(PWRKEY_PIN, LOW);

    delay(5000);

    Serial.println("Set Rset Pin hold low");
    // Keep it low during the sleep period. If the module uses GPIO5 as reset,
    // there will be a pulse when waking up from sleep that will cause the module to start directly.
    // https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/85
    digitalWrite(MODEM_RESET_PIN, !MODEM_RESET_LEVEL);
    gpio_hold_en((gpio_num_t)MODEM_RESET_PIN);
    gpio_deep_sleep_hold_en();


    Serial.println("Enter esp32 goto deepsleep!");
    esp_sleep_enable_timer_wakeup(TIME_TO_SLEEP * uS_TO_S_FACTOR);
    delay(200);
    esp_deep_sleep_start();
    Serial.println("This will never be printed");
}

void loop()
{
}
```

**Comment by pacmac** [comment]
I will try later, but if you short out the 2 pins then you cannot power off the modem, GPIO12 will always be HIGH.

Also, you have to sleep for 5 minutes, as it appears that the modem has capacitors that hold charge and if you sleep for such a short time you will not always see the problem.

**Comment by lewisxhe** [comment]
The current version cannot turn off the MODEM power supply, and can only be shut down through PWRKEY. If you want to keep the MOS tube, the problem will still occur.

**Comment by lewisxhe** [comment]
Sleep time does not affect it because it can be easily tested

**Comment by pacmac** [comment]
so your solution is to hold the MODEM reset pin high during sleep & release it on wakeup.

Wouldn't that also work on the POW_PIN ?

**Comment by lewisxhe** [comment]
Yes, the same applies. But if you don’t remove the MOS, the power consumption may increase. You can try this. At present, I think the reliable solution is to maintain DC power supply and switch the power on and off through PWRKEY.

**Comment by pacmac** [comment]
The SIMCOM hardware manual says that the reset sequence is only required if the modem becomes unresponsive to the PWK KEY and it is not necessary to run that sequence every time to power on.

**Comment by kgmuzungu** [comment]
![WhatsApp Bild 2024-09-13 um 12 21 23_f7e7580a_cr](https://github.com/user-attachments/assets/0f26ea42-6b28-494a-ba67-5d5995bd5760)

**Comment by kgmuzungu** [comment]
Indicate at least in the schema which transistor you short-cutted! This is soooo much wasted time!

**Comment by kgmuzungu** [comment]
@pacmac how did you get the serial monitor without having USB connected?

**Comment by btframework** [comment]
It is probably too late answer, but I have one T-A7608E bought few years ago (probably 2 or 3) so I guess it is one of the first version. I use it with battery powered without any issue. Here is the initialization sequence that works perfect in any case: does not matter if it is powered by USB or battery.

So, if the board should be power by battery the very first think I do is disable brown-out detection:

#include <soc/soc.h>
#include <soc/rtc_cntl_reg.h>

uint32_t State = WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0);

Next, you I initialize debug UART and right after that I initialize battery:

// Initialize onboard battery pins.
pinMode(BATT_18650_EN_PIN, OUTPUT);
pinMode(BATT_18650_ADC_PIN, INPUT);
// Enable onboard battery.
digitalWrite(BATT_18650_EN_PIN, HIGH);

Initialize modem pis to its initial state as described in A7608x manual:

// Initialize modem control pins.
pinMode(A7608H_DTR_PIN, OUTPUT);
pinMode(A7608H_RESET_PIN, OUTPUT);
pinMode(A7608H_PWRKEY_PIN, OUTPUT);
// Set modem pins to initial state.
digitalWrite(A7608H_DTR_PIN, LOW);
digitalWrite(A7608H_RESET_PIN, LOW);
digitalWrite(A7608H_PWRKEY_PIN, LOW);
// Initialize modem UART.
ModemSerial.begin(MODEM_UART_BAUD_RATE, SERIAL_8N1, A7608H_RX_PIN, A7608H_TX_PIN);

Next wait for about 5 seconds for modem startup. It is always powered up when board powered from USB and never if board powered from battery.

// Modem always turned on after reset. Wait for initialization.
ESP_LOGI(TAG_MODEM, "Wait for modem wake up");
delay(MODEM_WAKEUP_DELAY);

After that 5 seconds I check the modem status by sending AT command.

bool IsModemActive()
{
    ESP_LOGI(TAG_MODEM, "Testing modem response");

    // Clear modem stream.
    while (Modem.stream.available())
        Modem.stream.read();

    for (uint8_t i = 0; i < 2; i++)
    {
        ESP_LOGI(TAG_MODEM, "Test attempt: %u", i + 1);
        
        if (Modem.testAT(AT_TIMEOUT))
        {
            ESP_LOGI(TAG_MODEM, "Modem is OK");
            return true;
        }
        delay(MODEM_TEST_DELAY);
    }

    ESP_LOGI(TAG_MODEM, "Modem is not responding");
    return false;
}

If it does not response and I need it I turns it on using power-on sequence:

bool InitModem()
{
    ESP_LOGI(TAG_MODEM, "Modem initialization");

    // Check modem state.
    if (!IsModemActive())
    {
        ESP_LOGI(TAG_MODEM, "Power modem on");
        
        digitalWrite(A7608H_PWRKEY_PIN, HIGH);
        delay(POWER_ON_PULSE);
        
        digitalWrite(A7608H_PWRKEY_PIN, LOW);
        delay(POWER_ON_DELAY);
    }

    // Wait for modem initialization.
    uint8_t Retry = 0;
    bool ModemReady = false;
    while (!ModemReady && Retry++ < INIT_RETRY)
        ModemReady = IsModemActive();

    ESP_LOGI(TAG_MODEM, "Initialization completed: %s",
        ModemReady ? "Modem Ready" : "Modem Not Ready");
    return ModemReady;
}

Next I do what I need with modem and shut it down as described in its datasheet. First I try to send AT+CPOF command. If it failed I use the power-off sequence:

void PowerOffModem()
{
    ESP_LOGI(TAG_MODEM, "Turning modem off");
    
    // Try to turn modem off with AT command (software power off).
    Modem.sendAT("+CPOF");
    if (Modem.waitResponse(AT_TIMEOUT))
    {
        ESP_LOGI(TAG_MODEM, "Modem turned off with +CPOF command.");
        return;
    }

    if (!IsModemActive())
        return;
    
    ESP_LOGI(TAG_MODEM, "+CPOF failed. Use hardware power off sequence.");
    
    // If failed use power PINs (hardware power off).
    digitalWrite(A7608H_PWRKEY_PIN, HIGH);
    delay(POWER_OFF_PULSE);
    
    digitalWrite(A7608H_PWRKEY_PIN, LOW);
    delay(POWER_OFF_DELAY);
    
    ESP_LOGI(TAG_MODEM, "Modem powered off");
}

After that I put board in hybernation or deep sleep

void Hibernate(const bool Success)
{
    // Hibernate.
    if (Success)
    {
        ESP_LOGI(TAG_POWER, "Hibernating for long period [%u]",
            SLEEP_DURATION_SUCCESS);
    }
    else
    {
        ESP_LOGI(TAG_POWER, "Hibernating for short period [%u]",
            SLEEP_DURATION_FAILED);
    }

    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_ON);
    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_OFF);
    
    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_SLOW_MEM, ESP_PD_OPTION_ON);
    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_SLOW_MEM, ESP_PD_OPTION_OFF);
    
    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_FAST_MEM, ESP_PD_OPTION_ON);
    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_FAST_MEM, ESP_PD_OPTION_OFF);
    
    esp_sleep_pd_config(ESP_PD_DOMAIN_XTAL, ESP_PD_OPTION_ON);
    esp_sleep_pd_config(ESP_PD_DOMAIN_XTAL, ESP_PD_OPTION_OFF);
    
    if (Success)
        esp_sleep_enable_timer_wakeup(SLEEP_DURATION_SUCCESS);
    else
        esp_sleep_enable_timer_wakeup(SLEEP_DURATION_FAILED);
    esp_deep_sleep_start();
}

Works like a charm for past couple of years.
