### ISSUE TITLE
Precision regarding products

### ISSUE THREAD

**Issue by guilbaudl** [Xinyuan-LilyGO/LilyGO-T-A76XX#88]
Hello,
According to the table on the repo, it seems that T-A7670G is the most capable device you sell, especially regarding GPS.
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/57914748/480303b4-44c6-41e8-be62-a738cf259f36)

However, in this issue (https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/57) you are saying that it doesn't support GPS. 

What do I need to buy to support GPS out of the box? Do i need to buy an extra module?

**Comment by lewisxhe** [comment]
See https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/56#issuecomment-1672628977

**Comment by melkras** [comment]
What a dissapointment, I bought this product because of `GPS_Builtin` ✅.
