### ISSUE TITLE
No response from AT+CGNSSPWR=1 command

### ISSUE THREAD

**Issue by bconfais** [Xinyuan-LilyGO/LilyGO-T-A76XX#90]
I use a T-A7670E with LTE and GPS capabilities. Everything worked fine for many weeks but since we tried to upload a new sketch, the command ```AT+CGNSSPWR=1``` does not respond.
The LTE connection however works fine.

I flashed the card with the demo firmware (T-A7670X GPS Test firmware): https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/blob/main/firmware/README.MD but the problem is the same: the card enters in an infinite loop of sending ```AT+CGNSSPWR=1```, displays ```OK``` after the command but never receives the ```+CGNSSPWR: READY!```

Is there something to do in order to fix the card?

I thank you very much.
Bastien.

**Comment by lewisxhe** [comment]
Scan the QR code on the module. In addition to the IMEI number, other information will be sent to me. I will check whether it supports GPS.

**Comment by bconfais** [comment]
I thank you for you r quick reply.
The QRCode on the top of the chip codes the following information:

```
P/N:S2-10AAW-Z319S;SN:MP06230333D6566;IMEI:862205059130346;BTMAC:5C46B05EB024;SW:A011B04A7670M7_F
```

**Comment by lewisxhe** [comment]
I may have overlooked the GPIO. Please try this first to see if it can be used.

```
AT+CGDRT=4,1
AT+CGSETV=4,1
AT++CGNSSPWR=1
```

**Comment by lewisxhe** [comment]
Try it and tell me the result

**Comment by lewisxhe** [comment]
I just conducted a test. Even if you don't send AT+CGDRT=4,1, after starting correctly, send AT+CGNSSPWR=1 and wait for a few seconds, READY will appear. I suspect there is a problem with the GPS power supply. Please measure whether there is voltage on this Pin.
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/22990954/66db01e8-cd20-4782-9cb9-0ad5204c69b6)

**Comment by bconfais** [comment]
I thank you for your reply.

I sent the commands using the ATDebug.ino sketch available in the ```example``` folder.
Here is the result:

```
+CPIN: SIM PIN
*ATREADY: 1

AT+CPIN="1234"
OK
+CPIN: READY
SMS: DONE

AT+CGDRT=4,1
OK
PB DONE

AT+CGSETV=4,1
OK

AT+CGNSSPWR=1
OK
```

and additional commands ```AT+CGNSSPWR=1```  just prints ```OK``` and never prints the  ```+CGNSSPWR: READY!```

**Comment by bconfais** [comment]
We just performed the second test you  indicated. The measured voltage between the two pins you indicated is 1.8 V but the ```AT+CGNSSPWR=1 ``` still does not work.

**Comment by lewisxhe** [comment]
If the power supply is normal but there is no startup feedback, there may be an internal problem with the GPS. I suspect it is a hardware problem.

**Comment by lewisxhe** [comment]
Did you have no GPS feedback when you first received it?
Or does it appear after using it for a period of time?

**Comment by bconfais** [comment]
It has worked for more than a month and suddenly stopped after we flashed a new sketch 
(the new sketch was not very different from the one that worked - the modification consisted to adjust a sleeping period)

**Comment by Rehaell** [comment]
I just got my T-A7670E and I'm stuck on the AT+CGNSSPWR=1 OK loop too.

**Comment by lewisxhe** [comment]
Then the hardware may be damaged.

**Comment by takkienam** [comment]
Hi everyone,
I am using an A7670E module as well (although unrelated to this specific product) and I am stuck at the same problem. 
When issuing the command `AT+CGNSSPWR=1`, I get an `OK` back from the module, but `AT+CGNSSPWR=1` is never sent.
Has anyone found a solution or confirmation that this is a hardware issue?

**Comment by Rehaell** [comment]
> Hi everyone,
> I am using an A7670E module as well (although unrelated to this specific product) and I am stuck at the same problem. 
> When issuing the command `AT+CGNSSPWR=1`, I get an `OK` back from the module, but `AT+CGNSSPWR=1` is never sent.
> Has anyone found a solution or confirmation that this is a hardware issue?

Sorry, I ended up returning the board and creating my own.

**Comment by takkienam** [comment]
> > Hi everyone,
> > I am using an A7670E module as well (although unrelated to this specific product) and I am stuck at the same problem.
> > When issuing the command `AT+CGNSSPWR=1`, I get an `OK` back from the module, but `AT+CGNSSPWR=1` is never sent.
> > Has anyone found a solution or confirmation that this is a hardware issue?
> 
> Sorry, I ended up returning the board and creating my own.

Oh okay. Thanks for the reply :)

**Comment by OCMTemp** [comment]
Same board, same problem. It works most of the time but sometimes when I reboot it, it will get stuck in the loop. If I then power off the board and wait for 10 minutes, it will usually work again. I tried adding AT+CGDRT=4,1 and AT+CGSETV=4,1 before powering on my GPS modem, but it makes no difference.

Has anyone found a workaround?

**Comment by OCMTemp** [comment]
I tested voltage as described in the picture that you uploaded.

When the modem is working:
- Pin at left arrow: 1.8V
- Pin at right arrow: 1.8V

When the modem fails to start up:
- Pin at left arrow: 1.8V
- Pin at right arrow: 0.0V

![Image](https://github.com/user-attachments/assets/05422499-0f9d-4180-a7c5-fd90cba371d0)

**Comment by olalonde** [comment]
I have similar issue with A7672SA board. If I connect via UART and manually send `AT+CGNSSPWR=1`, it works  but if I try to use it  with cmux channel while other channel is in PPP mode, it doesn't work.

<img width="435" alt="Image" src="https://github.com/user-attachments/assets/40f0e4a6-7e89-4d39-a768-b64a2d413896" />
