### ISSUE TITLE
Battery boost convertor possibly failed. High pitch noise and modem not starting on battery

### ISSUE THREAD

**Issue by deeja** [Xinyuan-LilyGO/LilyGO-T-A76XX#92]
I have 2 boards (A7670SA and A7670G) that are making a high pitch noise when running off battery. 
When running off battery, 
1. there is a noise,
2. the modem doesn't power on, but the ESP module seems to work.

When running off USB, 
1. no noise
2. modem works

These boards have been running for a few months off solar.
Is there anything I can do to fix this?

**Comment by lewisxhe** [comment]
What voltage do you mean when the battery is exhausted?
The circuit uses a DCDC boost converter. The whistling should come from the inductor. It should be that the battery voltage is no longer enough for the booster to work.

**Comment by deeja** [comment]
Thanks for updating. The project I'm working on is somewhat on hold. I will do some tests and see what voltage they are cutting out at. I think it might be related to the antenna too, but I will need to check when I have some time
