### ISSUE TITLE
TLS 1.2 cipher suites

### ISSUE THREAD

**Issue by andrastimarsc** [Xinyuan-LilyGO/LilyGO-T-A76XX#94]
I am having an issue (715 - handshake error) with accessing some urls through HTTPS, whilst I can access others. It appears that the only difference between the ones I can access and those I cannot, is the offered cipher suites. Is there any way to update to a firmware that supports any of the following suites?
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/163282662/c0a4d249-0cba-457f-aaa2-d80070a9a266)
Or could anyone tell me what the supported ciphers are?

**Comment by lewisxhe** [comment]
There is currently no updated version of firmware
https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/issues/75
