### ISSUE TITLE
Difference between A7670 and TSIM7600

### ISSUE THREAD

**Issue by ChadMatsalla** [Xinyuan-LilyGO/LilyGO-T-A76XX#96]
Hi,

@lewisxhe perhaps?

Can anybody explain the difference between  the A7670 and TSIM7600?

I’m interested in battery and solar for a remote location in Canada. Schematics indicate that both have CN3065 for battery charging, both have on-board battery, battery protection 

T-SIM 7600
S-8205A for overcharge discharge protection
DW01FA for battery management
CN3065 for charging
ESP32 WROVER
JW5222 buck converter
ME6217 LDO
TCS9208 step-up
IO35 for battery voltage

A7670

RS0108YQ20 voltage level converter
XC6206P voltage regulator
ESP32WROVER
DW06D for battery protection
CN3065 for charging
RT9080 LDO ( or AP2112K )

A7670 seems much cheaper.

Chad

**Comment by lewisxhe** [comment]
A7670 is Cat1, Sim7600 is Cat4, the rates are different. Regarding the circuit board, both are the same solution, only the tuner and demodulator are different.

**Comment by engineerlewis00-coder** [comment]
But sim7600 is good if you need download speed of up to 150MBS/S and upload speed of 50MB/S
Also A7670 doesn't allow calls, 
If you need calling, sms, lacation, backup lte, use sim7600

**Comment by lewisxhe** [comment]
The A7670 has a budget version that doesn't support calls and SMS, while other standard versions do. I personally recommend the A7670 because its software is more mature and its power consumption is lower. The SIM7600 is an architecture from over a decade ago and has extremely high power consumption.
