### ISSUE TITLE
Difference between A7670G R1 and A7670G R2

### ISSUE THREAD

**Issue by ChadMatsalla** [Xinyuan-LilyGO/LilyGO-T-A76XX#98]
Hi!

I looked but could not find a document describing the differences between hardware versions. Can anybody help?

Should I make efforts to get R2 of the board or are they functionally equivalent?

Thanks,

Chad

**Comment by lewisxhe** [comment]
The only difference between them is the chip manufacturing process inside the modem. There is no difference in the usage.
