### ISSUE TITLE
i2c Question

### ISSUE THREAD

**Issue by randyb128** [Xinyuan-LilyGO/LilyGO-T-A76XX#99]
I want to connect an i2c DS3231 real time clock chip to I/O lines 21 and 22 of a LilyGO-T-A76XX device.  My question is, your schematic doesn't show any resistors on 21 or 22 but physically it looks like there might be a resistor pack connected on the back of the board to those pins.  (see picture)  It looks like it could be a pull down resistor.  If so, what is the value?
![48fb49ed-7531-474b-81dc-f212cd3a59ac](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/12303478/1154d86b-899c-40c8-a895-a637a5119f15)

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/assets/22990954/3cef211a-c959-49f8-8d73-826e20826995)
Resistors you can add externally, most modules come with their own resistors
